name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: apt-get update -qq
    - name: Install qt
      run: apt-get -y install qtdeclarative5-dev qt5-default
    - name: qmake
      env:
        QT_VERSION: 5
      run: qmake
    - name: make
      env:
        QT_VERSION: 5
      run: make
    
