name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: sudo apt-get update -qq
    - name: Install qt
      run: sudo apt-get -y install qtdeclarative5-dev
    - name: qmake
      env:
        QT_VERSION: 5
      run: qmake
    - name: make
      env:
        QT_VERSION: 5
      run: make
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        artifacts: "libdockwidget_plugin.so._VERSION_.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: _VERSION_.0.0
