name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
    - QT_VERSION=5
  
    steps:
    - uses: actions/checkout@v3
    - run: apt-get update -qq
    - run: apt-get install qtdeclarative5-dev qt5-default
    - name: configure
      run: ./configure
    - name: qmake
      run: qmake
    - name: make
      run: make
    
