name: Linux Build, no deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: update apt
      run: sudo apt-get update -qq
    - name: Install qt
      run: sudo apt-get -y install qtdeclarative5-dev
    - name: qmake
      env:
        QT_VERSION: 5
      run: qmake
    - name: make
      env:
        QT_VERSION: 5
      run: make

