name: win32/win64 Build and Deploy

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: 
          - windows-2019
        arch:
          - x64
          - x86
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2019
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: ${{ matrix.arch }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.arch == 'x64' && 'x64' || 'x86' }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.arch == 'x64' && 'win64_msvc2019_64' || 'win32_msvc2019' }}
          dir: '${{ github.workspace }}'
          install-deps: 'true'
          cache: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: 'false'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Build-arch
        run: |
          pwd
          ls .
          cmake -A ${{ matrix.arch == 'x64' && 'x64' || 'Win32' }} .
      - name: Build-release
        run: cmake --build . --config Release 
      - name: Rename release
        run: |
          mv release/DockWidget.dll DockWidget1.${{ matrix.os }}_${{ matrix.arch }}.dll
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}${{ matrix.arch }}
          path: DockWidget1.${{ matrix.os }}_${{ matrix.arch }}.dll

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Create Tmp Folder
        run: |
          mkdir -p tmp
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: tmp
      - name: Move artifacts to release
        run: |
          mv tmp/**/* deploy/plugins/
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r ../DockWidget.zip .
        working-directory: deploy
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: DockWidget.zip
          asset_name: DockWidget.ts3_plugin
          asset_content_type: application/zip
